# Global
domain: 
storageClass: "do-block-storage"
# Application specific
kyverno:
  enable: true  
logging:
  enable: true
observability:
  enable: true
  pdkey:
  storageSize: 50Gi
  retention: 5d
traefik:
  enable: true  
trivy:
  enable: true
